set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(CMAKE_C_COMPILER gcc CACHE STRING "")
set(CMAKE_ASM_COMPILER gcc CACHE STRING "")
set(CMAKE_CXX_COMPILER g++ CACHE STRING "")
set(CMAKE_Fortran_COMPILER gfortran CACHE STRING "")
set(CMAKE_COMPILER_IS_GNUCC ON CACHE BOOL "")
set(CMAKE_COMPILER_IS_GNUCXX ON CACHE BOOL "")

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(LINKER_EXECUTABLE ld.gold CACHE FILEPATH "")
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=gold ${VCPKG_LINKER_FLAGS}" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} CACHE STRING "")

if (NOT VCPKG_ALLOW_SYSTEM_LIBS)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
endif ()