set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET v142)

if (VCPKG_CLANG_PATH)
    file(TO_CMAKE_PATH "${VCPKG_CLANG_PATH}" _CLANG_PREFIX)
endif()

set(CMAKE_C_COMPILER ${_CLANG_PREFIX}/clang.exe CACHE STRING "")
set(CMAKE_CXX_COMPILER ${_CLANG_PREFIX}/clang++.exe CACHE STRING "")
set(CMAKE_RC_COMPILER ${_CLANG_PREFIX}/llvm-rc.exe CACHE STRING "")
set(CMAKE_LINKER ${_CLANG_PREFIX}/lld-link.exe CACHE STRING "")

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")