set(VCPKG_TARGET_ARCHITECTURE x64 CACHE STRING "")
set(VCPKG_CRT_LINKAGE static CACHE STRING "")
set(VCPKG_LIBRARY_LINKAGE static CACHE STRING "")
set(VCPKG_PLATFORM_TOOLSET v143 CACHE STRING "")
set(VCPKG_SET_CHARSET_FLAG ON CACHE BOOL "")

set(VCPKG_C_FLAGS_RELEASE "/GL" CACHE STRING "")
set(VCPKG_CXX_FLAGS_RELEASE "/GL" CACHE STRING "")
set(VCPKG_LINKER_FLAGS_RELEASE "/LTCG" CACHE STRING "")