set(VCPKG_TARGET_ARCHITECTURE x86 CACHE STRING "")
set(VCPKG_CRT_LINKAGE static CACHE STRING "")
set(VCPKG_LIBRARY_LINKAGE static CACHE STRING "")
set(VCPKG_PLATFORM_TOOLSET v142 CACHE STRING "")
set(VCPKG_SET_CHARSET_FLAG ON CACHE BOOL "")

