set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
set(VCPKG_BUILD_TYPE release)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO pcraster/pcraster
    REF v${VERSION}
    SHA512 e9676b164735336b445cb9b4ba09db61efa99c30d60caed96965854ea4c208385dc75328635284084b6b2330bb8b286f220c70742e88c5714fb95f90d1de1ac2
    HEAD_REF master
    PATCHES
        minimize-build.patch
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DPCRASTER_BUILD_DOCUMENTATION=OFF
        -DPCRASTER_BUILD_TEST=OFF
        -DPCRASTER_BUILD_AGUILA=OFF
        -DPCRASTER_BUILD_MODFLOW=ON
        -DPCRASTER_BUILD_MULTICORE=OFF
        -DPCRASTER_BUILD_BLOCKPYTHON=OFF
        -DPCRASTER_BUILD_MLDD=OFF
        -DPCRASTER_BUILD_MOC=OFF
        -DFERN_BUILD_ALGORITHM=TRUE
        -DHAVE_PYBIND11=ON
        -DBoost_USE_STATIC_LIBS=ON
        -DBoost_USE_STATIC_RUNTIME=ON
)

vcpkg_install_cmake()
vcpkg_copy_pdbs()

file(GLOB PCRASTER_BINARIES ${CURRENT_PACKAGES_DIR}/bin/*)
file(COPY ${PCRASTER_BINARIES} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/)

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/bin"
    "${CURRENT_PACKAGES_DIR}/doc"
    "${CURRENT_PACKAGES_DIR}/lib"
    "${CURRENT_PACKAGES_DIR}/include"
    "${CURRENT_PACKAGES_DIR}/share/gdal"
)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
