if(NOT _VCPKG_INTEL_TOOLCHAIN)
   set(_VCPKG_INTEL_TOOLCHAIN 1)

   if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
      set(CMAKE_CROSSCOMPILING OFF CACHE BOOL "")
   endif()

   set(CMAKE_SYSTEM_NAME Windows CACHE STRING "" FORCE)

   if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
      set(CMAKE_SYSTEM_PROCESSOR i686 CACHE STRING "")
   elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
      set(CMAKE_SYSTEM_PROCESSOR x86_64 CACHE STRING "")
   elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
      set(CMAKE_SYSTEM_PROCESSOR armv7 CACHE STRING "")
   elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
      set(CMAKE_SYSTEM_PROCESSOR aarch64 CACHE STRING "")
   endif()

   set(CMAKE_C_COMPILER "icx" CACHE STRING "" FORCE)
   set(CMAKE_CXX_COMPILER "icx" CACHE STRING "" FORCE)
   set(CMAKE_Fortran_COMPILER "ifx" CACHE STRING "" FORCE)

   get_property(_CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE)

   if(NOT _CMAKE_IN_TRY_COMPILE)
      if(VCPKG_C_FLAGS)
         list(APPEND CMAKE_C_FLAGS_INIT ${VCPKG_C_FLAGS})
      endif()

      if(VCPKG_CXX_FLAGS)
         list(APPEND CMAKE_CXX_FLAGS_INIT ${VCPKG_CXX_FLAGS})
      endif()

      if(VCPKG_C_FLAGS_DEBUG)
         list(APPEND CMAKE_C_FLAGS_DEBUG_INIT ${VCPKG_C_FLAGS_DEBUG})
      endif()

      if(VCPKG_CXX_FLAGS_DEBUG)
         list(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT ${VCPKG_CXX_FLAGS_DEBUG})
      endif()

      if(VCPKG_C_FLAGS_RELEASE)
         list(APPEND CMAKE_C_FLAGS_RELEASE_INIT ${VCPKG_C_FLAGS_RELEASE})
      endif()

      if(VCPKG_CXX_FLAGS_RELEASE)
         list(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT ${VCPKG_CXX_FLAGS_RELEASE})
      endif()

      if(VCPKG_LINKER_FLAGS)
         list(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT ${VCPKG_LINKER_FLAGS})
         list(APPEND CMAKE_EXE_LINKER_FLAGS_INIT ${VCPKG_LINKER_FLAGS})
      endif()

      if(VCPKG_CRT_LINKAGE STREQUAL "static")
         list(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT "-static")
         list(APPEND CMAKE_EXE_LINKER_FLAGS_INIT "-static")
      endif()

      if(VCPKG_LINKER_FLAGS_DEBUG)
         list(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT ${VCPKG_LINKER_FLAGS_DEBUG})
         list(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT ${VCPKG_LINKER_FLAGS_DEBUG})
      endif()

      if(VCPKG_LINKER_FLAGS_DEBUG)
         list(APPEND CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT ${VCPKG_LINKER_FLAGS_RELEASE})
         list(APPEND CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT ${VCPKG_LINKER_FLAGS_RELEASE})
      endif()
   endif()
endif()
